/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Java_project_SGU.GUI;

import Java_project_SGU.DAL.Write_ReadMovieToSqlImp;
import Java_project_SGU.Controller.MouseActionListenerHomeCus;
import Java_project_SGU.BUS.ClassListMovie;
import Java_project_SGU.BUS.Customer;
import Java_project_SGU.BUS.Movie;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class HomePageCusFrm extends javax.swing.JFrame implements ActionListener {
    private CardLayout cardLayout;
    private ClassListMovie classListMovie;
    private ArrayList<JPanel> listPanelMovie;
    private Customer customer;
    private List<JLabel> listDeltaiMVLB;
    private boolean isOpenMenu;
    
    /**
     * Creates new form HomePageCusFrm
     */
    public HomePageCusFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        cardLayout = (CardLayout) CardPN.getLayout();
        loadDataFromSQL();
        loadListMovieToHomePage();
        addActiontionListener();
        isOpenMenu = false;
        
    }
    
    public HomePageCusFrm(Customer customer) {
        this();
        this.customer = customer;
        initHomePageCus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        movieShowingEvent = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        foodShowingEvent = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        CardPN = new javax.swing.JPanel();
        CardFoodLayout = new javax.swing.JPanel();
        blockMenuPN1 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        infoCusIMenu1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        logoutMenu1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CardMovieLayout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        searchMovieTxt = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        panelDisplayMovies = new javax.swing.JPanel();
        blockMenuPN2 = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        infoCusIMenu2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        logoutMenu2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        searchNameMVBtn = new javax.swing.JButton();
        menuIcon = new javax.swing.JLabel();
        informOfCus = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Java_project_SGU/Image/movie_heading.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DDH");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cinema");

        movieShowingEvent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        movieShowingEvent.setForeground(new java.awt.Color(255, 255, 255));
        movieShowingEvent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movieShowingEvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Java_project_SGU/Image/movieShowingCus.png"))); // NOI18N
        movieShowingEvent.setText("Phim Đang Chiếu");
        movieShowingEvent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        foodShowingEvent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        foodShowingEvent.setForeground(new java.awt.Color(255, 255, 255));
        foodShowingEvent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodShowingEvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Java_project_SGU/Image/Artdesigner-Urban-Stories-Coffee.32.png"))); // NOI18N
        foodShowingEvent.setText("Đồ Ăn & uống");
        foodShowingEvent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(movieShowingEvent, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
            .addComponent(foodShowingEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(movieShowingEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(foodShowingEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CardPN.setLayout(new java.awt.CardLayout());

        blockMenuPN1.setBackground(new java.awt.Color(153, 0, 153));
        blockMenuPN1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 1, true));
        blockMenuPN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSeparator6.setBackground(new java.awt.Color(153, 0, 153));

        infoCusIMenu1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Java_project_SGU/Image/customer.png"))); // NOI18N

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Thông Tin Cá Nhân");

        javax.swing.GroupLayout infoCusIMenu1Layout = new javax.swing.GroupLayout(infoCusIMenu1);
        infoCusIMenu1.setLayout(infoCusIMenu1Layout);
        infoCusIMenu1Layout.setHorizontalGroup(
            infoCusIMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoCusIMenu1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        infoCusIMenu1Layout.setVerticalGroup(
            infoCusIMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        logoutMenu1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Java_project_SGU/Image/login_icon.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Đăng Xuất");

        javax.swing.GroupLayout logoutMenu1Layout = new javax.swing.GroupLayout(logoutMenu1);
        logoutMenu1.setLayout(logoutMenu1Layout);
        logoutMenu1Layout.setHorizontalGroup(
            logoutMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutMenu1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoutMenu1Layout.setVerticalGroup(
            logoutMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout blockMenuPN1Layout = new javax.swing.GroupLayout(blockMenuPN1);
        blockMenuPN1.setLayout(blockMenuPN1Layout);
        blockMenuPN1Layout.setHorizontalGroup(
            blockMenuPN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoCusIMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(blockMenuPN1Layout.createSequentialGroup()
                .addGroup(blockMenuPN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        blockMenuPN1Layout.setVerticalGroup(
            blockMenuPN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockMenuPN1Layout.createSequentialGroup()
                .addComponent(infoCusIMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoutMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout CardFoodLayoutLayout = new javax.swing.GroupLayout(CardFoodLayout);
        CardFoodLayout.setLayout(CardFoodLayoutLayout);
        CardFoodLayoutLayout.setHorizontalGroup(
            CardFoodLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardFoodLayoutLayout.createSequentialGroup()
                .addGap(0, 1075, Short.MAX_VALUE)
                .addComponent(blockMenuPN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CardFoodLayoutLayout.setVerticalGroup(
            CardFoodLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardFoodLayoutLayout.createSequentialGroup()
                .addComponent(blockMenuPN1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 697, Short.MAX_VALUE))
        );

        CardPN.add(CardFoodLayout, "card2");

        CardMovieLayout.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Phim Đang Chiếu");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 153));
        jLabel8.setText("Tìm Tên Phim:");

        searchMovieTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchMovieTxt.setForeground(new java.awt.Color(153, 0, 153));
        searchMovieTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 0, 153)));

        jScrollPane4.setHorizontalScrollBar(null);

        panelDisplayMovies.setPreferredSize(new java.awt.Dimension(1248, 10000));
        panelDisplayMovies.setLayout(null);
        jScrollPane4.setViewportView(panelDisplayMovies);

        blockMenuPN2.setBackground(new java.awt.Color(153, 0, 153));
        blockMenuPN2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));

        jSeparator7.setBackground(new java.awt.Color(153, 0, 153));

        infoCusIMenu2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Java_project_SGU/Image/customer.png"))); // NOI18N

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Thông Tin Cá Nhân");

        javax.swing.GroupLayout infoCusIMenu2Layout = new javax.swing.GroupLayout(infoCusIMenu2);
        infoCusIMenu2.setLayout(infoCusIMenu2Layout);
        infoCusIMenu2Layout.setHorizontalGroup(
            infoCusIMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoCusIMenu2Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        infoCusIMenu2Layout.setVerticalGroup(
            infoCusIMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        logoutMenu2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Java_project_SGU/Image/login_icon.png"))); // NOI18N

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Đăng Xuất");

        javax.swing.GroupLayout logoutMenu2Layout = new javax.swing.GroupLayout(logoutMenu2);
        logoutMenu2.setLayout(logoutMenu2Layout);
        logoutMenu2Layout.setHorizontalGroup(
            logoutMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutMenu2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoutMenu2Layout.setVerticalGroup(
            logoutMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout blockMenuPN2Layout = new javax.swing.GroupLayout(blockMenuPN2);
        blockMenuPN2.setLayout(blockMenuPN2Layout);
        blockMenuPN2Layout.setHorizontalGroup(
            blockMenuPN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoCusIMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(blockMenuPN2Layout.createSequentialGroup()
                .addGroup(blockMenuPN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        blockMenuPN2Layout.setVerticalGroup(
            blockMenuPN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockMenuPN2Layout.createSequentialGroup()
                .addComponent(infoCusIMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoutMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        searchNameMVBtn.setBackground(new java.awt.Color(153, 0, 153));
        searchNameMVBtn.setForeground(new java.awt.Color(255, 153, 51));
        searchNameMVBtn.setText("Tìm Kiếm");
        searchNameMVBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout CardMovieLayoutLayout = new javax.swing.GroupLayout(CardMovieLayout);
        CardMovieLayout.setLayout(CardMovieLayoutLayout);
        CardMovieLayoutLayout.setHorizontalGroup(
            CardMovieLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardMovieLayoutLayout.createSequentialGroup()
                .addGap(0, 1075, Short.MAX_VALUE)
                .addComponent(blockMenuPN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(CardMovieLayoutLayout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addComponent(searchMovieTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(searchNameMVBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CardMovieLayoutLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(CardMovieLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1289, Short.MAX_VALUE))
        );
        CardMovieLayoutLayout.setVerticalGroup(
            CardMovieLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardMovieLayoutLayout.createSequentialGroup()
                .addComponent(blockMenuPN2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(CardMovieLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchMovieTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchNameMVBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(571, Short.MAX_VALUE))
            .addGroup(CardMovieLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardMovieLayoutLayout.createSequentialGroup()
                    .addGap(0, 126, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        CardPN.add(CardMovieLayout, "card3");

        menuIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Java_project_SGU/Image/mene_icon.png"))); // NOI18N
        menuIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        informOfCus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        informOfCus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Java_project_SGU/Image/UserOfCus.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CardPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(informOfCus, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(informOfCus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(CardPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageCusFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageCusFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageCusFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageCusFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageCusFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardFoodLayout;
    private javax.swing.JPanel CardMovieLayout;
    private javax.swing.JPanel CardPN;
    private javax.swing.JPanel blockMenuPN1;
    private javax.swing.JPanel blockMenuPN2;
    private javax.swing.JLabel foodShowingEvent;
    private javax.swing.JPanel infoCusIMenu1;
    private javax.swing.JPanel infoCusIMenu2;
    private javax.swing.JLabel informOfCus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel logoutMenu1;
    private javax.swing.JPanel logoutMenu2;
    private javax.swing.JLabel menuIcon;
    private javax.swing.JLabel movieShowingEvent;
    private javax.swing.JPanel panelDisplayMovies;
    private javax.swing.JTextField searchMovieTxt;
    private javax.swing.JButton searchNameMVBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Object src = e.getSource();
        if (src.equals(this.movieShowingEvent)) {
            movieShowingEvent.setForeground(new java.awt.Color(153, 0, 153));
            movieShowingEvent.setBackground(Color.WHITE);
        }
    }

    private void addActiontionListener() {
        MouseActionListenerHomeCus mouseEvent = new MouseActionListenerHomeCus(this);
        this.movieShowingEvent.addMouseListener(mouseEvent);
        this.foodShowingEvent.addMouseListener(mouseEvent);
        this.logoutMenu1.addMouseListener(mouseEvent);
        this.infoCusIMenu1.addMouseListener(mouseEvent);
        this.logoutMenu2.addMouseListener(mouseEvent);
        this.infoCusIMenu2.addMouseListener(mouseEvent);
        //add all action to panel of list Movies\
//        for (int i = 0; i < listPanelMovie.size(); i++) {
//            this.listPanelMovie.get(i).addMouseListener(mouseEvent);
//        }
//        for (int i = 0; i < listDeltaiMVLB.size(); i++) {
//            listDeltaiMVLB.get(i).addMouseListener(mouseEvent);
//        }
        menuIcon.addMouseListener(mouseEvent);
        this.searchNameMVBtn.addMouseListener(mouseEvent);
    }

    public JLabel getMovieShowingEvent() {
        return movieShowingEvent;
    }

    public JButton getSearchNameMVBtn() {
        return searchNameMVBtn;
    }    

    public JLabel getFoodShowingEvent() {
        return foodShowingEvent;
    }

    public JLabel getMenuIcon() {
        return menuIcon;
    }

    public boolean isIsOpenMenu() {
        return isOpenMenu;
    }
    
    public ArrayList<JPanel> getListPanelMovie() {
        return listPanelMovie;
    }

    public List<JLabel> getListDeltaiMVLB() {
        return listDeltaiMVLB;
    }

    public JPanel getInfoCusIMenu1() {
        return infoCusIMenu1;
    }

    public JPanel getInfoCusIMenu2() {
        return infoCusIMenu2;
    }

    public JPanel getLogoutMenu1() {
        return logoutMenu1;
    }

    public JPanel getLogoutMenu2() {
        return logoutMenu2;
    }
    
    
    public void changeColorMovieShowing() {
        this.movieShowingEvent.setForeground(new java.awt.Color(153, 0, 153));
        this.movieShowingEvent.setBackground(Color.WHITE);
        this.movieShowingEvent.setOpaque(true);
    }
    
    public void changeOrigColorMovieShowing() {
        this.movieShowingEvent.setForeground(Color.WHITE);
        this.movieShowingEvent.setBackground(new java.awt.Color(153, 0, 153));
        this.movieShowingEvent.setOpaque(true);
    }
    
    public void changeColorFoodShowing() {
        this.foodShowingEvent.setForeground(new java.awt.Color(153, 0, 153));
        this.foodShowingEvent.setBackground(Color.WHITE);
        this.foodShowingEvent.setOpaque(true);
    }
    
    public void changeOrigColorFoodShowing() {
        this.foodShowingEvent.setForeground(Color.WHITE);
        this.foodShowingEvent.setBackground(new java.awt.Color(153, 0, 153));
        this.foodShowingEvent.setOpaque(true);
    }

    public void showCardMovie() {
        cardLayout.last(CardPN);
        System.out.println("movie");
    }

    public void showCardFood() {
        cardLayout.first(CardPN);
        System.out.println("food");
    }
    
     private void initHomePageCus() {
        this.informOfCus.setText(customer.getFullName());
    }

    private void loadDataFromSQL() {
        loadMovieFromSQL();
    }

    private void loadMovieFromSQL() {
        this.classListMovie = new ClassListMovie();
        Write_ReadMovieToSqlImp wrMovieSQL = new Write_ReadMovieToSqlImp();
        this.classListMovie.setMovies(wrMovieSQL.readMovieFromDS());
    }
    
    private void loadListMovieToHomePage() {
        this.panelDisplayMovies.removeAll();
        this.panelDisplayMovies.setLayout(new FlowLayout(FlowLayout.CENTER, 50, 50));
        this.listPanelMovie = new ArrayList<>();
        this.listDeltaiMVLB = new ArrayList<>();
        
        Font myFont = new Font("Arial", Font.BOLD, 14);
        for (int i = 0; i < classListMovie.getMovies().size(); i++) {
            JPanel individualMoviePN = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 10));
            individualMoviePN.setBackground(new java.awt.Color(153, 0, 153));
//            individualMoviePN.setSize(260, 450);
             individualMoviePN.setPreferredSize(new Dimension(260, 464));
//            jPanel.setMinimumSize(jPanel.getPreferredSize());
//            jPanel.setMaximumSize(jPanel.getPreferredSize());
            individualMoviePN.setCursor(new Cursor(Cursor.HAND_CURSOR));
            
            JLabel movieNameLB = new JLabel("TÊN PHIM: " + classListMovie.getMovies()
                    .get(i).getNameMovie());
            movieNameLB.setFont(myFont);
            movieNameLB.setForeground(Color.WHITE);
            
            JLabel imageLB = new JLabel();
            imageLB.setSize(240, 355);
            imageLB.setIcon(new ImageIcon(classListMovie.
                    getMovies().get(i).getLinkImage()));
            
            JLabel typeOfMovie = new JLabel("Thể Loại: " + classListMovie.getMovies()
                    .get(i).getTypeMovie());
            typeOfMovie.setFont(myFont);
            typeOfMovie.setForeground(Color.WHITE);
            
            JLabel detailLB = new JLabel("Chi tiết phim");
            detailLB.setBackground(Color.red);
            detailLB.setFont(myFont);
            detailLB.setCursor(new Cursor(Cursor.HAND_CURSOR));
            detailLB.setOpaque(true);
            detailLB.setForeground(Color.WHITE);
            
            individualMoviePN.add(imageLB);
            individualMoviePN.add(movieNameLB);
            individualMoviePN.add(typeOfMovie);
            individualMoviePN.add(detailLB);
            
            listDeltaiMVLB.add(detailLB);
            listPanelMovie.add(individualMoviePN);
            this.panelDisplayMovies.add(listPanelMovie.get(i));
        }
        
        addNewAction();
        //Refresh page
        this.panelDisplayMovies.repaint();
        this.panelDisplayMovies.revalidate();
    }
          
    public void changeColorPanel(int i) {
        this.listPanelMovie.get(i).setBackground(new java.awt.Color(255,153,0));
    }

    public void changeColorOrigPanel(int i) {
        this.listPanelMovie.get(i).setBackground(new java.awt.Color(153, 0, 153));
    }

    public void showDialogDeltailMovie(int i) {
        DetailMovieDialog detailMovieDialog = new DetailMovieDialog(this,
                true, classListMovie.getMovies().get(i));
        detailMovieDialog.setVisible(true);
    }
    
    public void showDialogChooseMovie(int indexPanelChoosen) {
        ChooseMovieDialog chooseMovieDialog = new ChooseMovieDialog
        (this, rootPaneCheckingEnabled, classListMovie
                .getMovies().get(indexPanelChoosen), customer);
        chooseMovieDialog.setVisible(true);
    }

    public void showMenuBlock() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i <= 82; i++) {
                    try {
                        Thread.sleep(3);
                        blockMenuPN1.setSize(200, i);
                        blockMenuPN2.setSize(200, i);
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                }
                isOpenMenu = true;
            }
        }).start();
    }
    
    
    public void closeMenuBlock() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 82; i >= 0; i--) {
                    try {
                        Thread.sleep(3);
                        blockMenuPN1.setSize(200, i);
                        blockMenuPN2.setSize(200, i);
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                }
                isOpenMenu = false;
            }
        }).start();
    }

    public void logout() {
        this.dispose();
        LoginFrm loginFrm = new LoginFrm();
        loginFrm.setVisible(true);
    }

    public void changeBackgroundItemMN() {
        
    }

    public void changeBackgroundItem1MN() {
        this.infoCusIMenu1.setBackground(Color.lightGray);
        this.infoCusIMenu2.setBackground(Color.lightGray);
    }

    public void changeBackgroundItem2MN() {
        this.logoutMenu1.setBackground(Color.lightGray);
        this.logoutMenu2.setBackground(Color.lightGray);
    }       

    public void changeOrigBackgroundItem1MN() {
        this.infoCusIMenu1.setBackground(Color.WHITE);
        this.infoCusIMenu2.setBackground(Color.WHITE);
    }

    public void changeOrigBackgroundItem2MN() {
        this.logoutMenu1.setBackground(Color.WHITE);
        this.logoutMenu2.setBackground(Color.WHITE);
    }

    public void renderMVsByNameSearch() {
        String nameSearch = this.searchMovieTxt.getText();     
        this.loadMovieFromSQL();
        this.classListMovie.fillMovieBySearchName(nameSearch);
//        for (Movie movie : this.classListMovie.getMovies()) {
//            System.out.println(movie.getNameMovie());
//        }
//        System.out.println(classListMovie.getMovies().size());
        loadListMovieToHomePage();
    }

    private void addNewAction() {
        MouseActionListenerHomeCus mouseEvent = new MouseActionListenerHomeCus(this);
        for (int i = 0; i < listPanelMovie.size(); i++) {
            this.listPanelMovie.get(i).addMouseListener(mouseEvent);
        }
        for (int i = 0; i < listDeltaiMVLB.size(); i++) {
            listDeltaiMVLB.get(i).addMouseListener(mouseEvent);
        }
    }
}
